version: "3.9"

volumes:
  db_data: {}

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - 8080:80
    # network_mode: host

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: ProductionApi
    ports:
      - 4000:4000
    env_file:
      - .env

    stdin_open: true
    networks:
      nest_backend:

    # network_mode: host

  # Database service
  db:
    # pull image from docker hub
    image: mongo
    # container name
    container_name: nestmongo
    # always restart the container if it stops.
    restart: always
    # database credentials, this is take value from env file
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    # save (persist) data and also to share data between containers
    volumes:
      - db_data:/data/db
    # database port
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    # application network, each container for a service joins this network
    networks:
      - nest_backend

# Rename the default network so we can easily identify it
# Across all containers
networks:
  nest_backend:
    driver: bridge
